name: dadosabertos
channels: !!python/tuple
- conda-forge
- defaults
dependencies:
- conda-forge::ca-certificates=2017.4.17=0
- conda-forge::certifi=2017.4.17=py36_0
- conda-forge::colorama=0.3.9=py36_0
- conda-forge::cycler=0.10.0=py36_0
- conda-forge::decorator=4.0.11=py36_0
- conda-forge::freetype=2.7=vc14_1
- conda-forge::git=2.12.2=4
- conda-forge::icu=58.1=vc14_1
- conda-forge::ipykernel=4.6.1=py36_0
- conda-forge::ipython=6.1.0=py36_0
- conda-forge::ipython_genutils=0.2.0=py36_0
- conda-forge::jedi=0.10.0=py36_0
- conda-forge::jpeg=9b=vc14_0
- conda-forge::jupyter_client=5.0.1=py36_0
- conda-forge::jupyter_core=4.3.0=py36_0
- conda-forge::libpng=1.6.28=vc14_0
- conda-forge::matplotlib=2.0.2=np112py36_0
- conda-forge::openssl=1.0.2h=vc14_3
- conda-forge::pandas=0.20.1=np112py36_0
- conda-forge::patsy=0.4.1=py36_0
- conda-forge::pickleshare=0.7.3=py36_0
- conda-forge::pip=9.0.1=py36_0
- conda-forge::prompt_toolkit=1.0.14=py36_0
- conda-forge::pygments=2.2.0=py36_0
- conda-forge::pyparsing=2.2.0=py36_0
- conda-forge::pyqt=5.6.0=py36_3
- conda-forge::python=3.6.1=3
- conda-forge::python-dateutil=2.6.0=py36_0
- conda-forge::pytz=2017.2=py36_0
- conda-forge::pyzmq=16.0.2=py36_2
- conda-forge::qt=5.6.2=vc14_1
- conda-forge::seaborn=0.7.1=py36_0
- conda-forge::setuptools=33.1.1=py36_0
- conda-forge::simplegeneric=0.8.1=py36_0
- conda-forge::sip=4.18=py36_1
- conda-forge::six=1.10.0=py36_1
- conda-forge::statsmodels=0.8.0=np112py36_0
- conda-forge::tornado=4.5.1=py36_0
- conda-forge::traitlets=4.3.2=py36_0
- conda-forge::vc=14=0
- conda-forge::vs2015_runtime=14.0.25420=0
- conda-forge::wcwidth=0.1.7=py36_0
- conda-forge::wheel=0.29.0=py36_0
- conda-forge::wincertstore=0.2=py36_0
- conda-forge::zlib=1.2.11=vc14_0
- mkl=2017.0.1=0
- numpy=1.12.1=py36_0
- scikit-learn=0.18.1=np112py36_1
- scipy=0.19.0=np112py36_0
- pip:
  - ipython-genutils==0.2.0
  - jupyter-client==5.0.1
  - jupyter-core==4.3.0
  - prompt-toolkit==1.0.14

